# Generated by Django 4.1 on 2022-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Imagen prueba', max_length=10),
            preserve_default=False,
        ),
    ]
