# Generated by Django 4.1 on 2022-09-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_image', '0003_image_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='archivo',
        ),
    ]
